### ISSUE TITLE
Allow aggregate method with opt

### ISSUE THREAD

**Issue by amz** [EqualExperts/mongo-shell-like-query#6]
MongoQueryParser parser = new MongoQueryParser();
                MongoQuery mongoQuery = parser.parse(longQuery, new HashMap());
                BasicDBList dbObjList = mongoQuery.execute(db);

Query is an aggregation: `db.events.aggregate([....])`

I have an exception: Caused by: com.mongodb.MongoCommandException: Command failed with error 16945: 'Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in.

When i try to pass it like: `db.events.aggregate([....],{ allowDiskUse: true })` then i have an exception: 
java.lang.RuntimeException: invalid query
	at com.ee.dynamicmongoquery.MongoQueryParser.parse(MongoQueryParser.scala:31)
	at com.ee.dynamicmongoquery.MongoQueryParser.parse(MongoQueryParser.scala:27)
......
Caused by: java.lang.ClassCastException: null

How can i pass allowDiskUse:true to query?

**Comment by amz** [comment]
I have created pull request to fix this https://github.com/EqualExperts/mongo-shell-like-query/pull/7
